//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;

public class Activités
{

    private int idActivité;
    private int horaireDebut; //Debut de l'activité en nombre de minute de 0 * 1480
    private string texteDescriptif;
    private string typeActivite;
    private int horaireFin; //Fin de l'activité en nombre de minute de 0 * 1480
    private string statutActivite;
    private Lieu lieuActivite;
    private static int nbActivité = 0;
    private string nomActivité;

    private List<Astronautes> listeAstronautes = new List<Astronautes>();
    //Constructeur par défaut
    public Activités(string nom, string type, int hDebut, int hFin, Lieu tempLieuActivite, List<Astronautes> tempListeAstronautes, string tempTexteDescriptif)
    {
        nbActivité++;
        nomActivité = nom;
        idActivité = nbActivité;
        horaireDebut = hDebut;
        horaireFin = hFin;
        typeActivite = type;
        lieuActivite = tempLieuActivite;
        listeAstronautes = tempListeAstronautes;
        texteDescriptif = tempTexteDescriptif;
    }



  

    //Accesseurs//
    public string GetNomActivité
    {
        get { return nomActivité; }
        set { nomActivité = value; }
    }


   
    public string getHoraireDebutMarsTexte()
    {

        string heure;
        if (getHeureDebutMars() == 0)
        {
            heure = "00";
        }
        else
        {
            heure = getHeureDebutMars().ToString();
        }

        string minute;
        if (getMinuteDebutMars() == 0)
        {
            minute = "00";
        }
        else
        {
            minute = getMinuteDebutMars().ToString();
        }

        string heureTexte = heure + "h" + minute;

        return heureTexte;
        
    }

    public int getHeureDebutMars()
    {
        double heureDouble = horaireDebut / 60;
        int heure = (int)Math.Truncate(heureDouble);

        return heure;

    }

    public int getMinuteDebutMars()
    {
        int minute = horaireDebut % 60;

        return minute;

    }

    public string getHoraireFinMarsTexte()
    {

        string heure;
        if (getHeureFinMars() == 0)
        {
            heure = "00";
        }
        else
        {
            heure = getHeureFinMars().ToString();
        }


        string minute;
        if (getMinuteFinMars() == 0)
        { 
            minute = "00";
        }
        else
        {
            minute = getMinuteFinMars().ToString();
        }

        string heureTexte = heure + "h" + minute;

        return heureTexte;

    }

    public int getHeureFinMars()
    {
        double heureDouble = horaireFin / 60;
        int heure = (int)Math.Truncate(heureDouble);

        return heure;

    }

    public int getMinuteFinMars()
    {
        int minute = horaireFin % 60;

        return minute;
    }


	public int getHoraireDebut
	{
		get { return horaireDebut; }
        set { horaireDebut = value; }
	}

	public int GetHoraireFin
	{
		get{return horaireFin;}
        set { horaireFin = value; }
	}

	public string GettexteDescriptif
	{
		get{return texteDescriptif;}
		set{texteDescriptif=value;}
	}

	public string GettypeActivite
	{
		get{return typeActivite;}
		set{typeActivite=value;}
	}

	public string GetstatutActivite
	{
		get{return statutActivite; }
		set{statutActivite =value;}
	}

    public Lieu GetLieuActivite
    {
        get { return lieuActivite; }
        set { lieuActivite = value; }
    }


	public virtual List<Astronautes> GetlisteAstronautes
	{
        get { return listeAstronautes; }
        set { listeAstronautes = value; }
	}

    public string GetnomActivite
    {
        get{return nomActivité;}
        set { nomActivité = value; }
    }
    public int GetnbActivité
    {
        get { return nbActivité; }
        set { nbActivité = value; }
    }

    public string GetnomLieuDeActivite
    {
        get{return this.lieuActivite.GetnomLieu;}
        
    }

        
    //FinAccesseurs


	public virtual void RenvoieActiviteParMotCle()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ajouterLieu()
	{
		throw new System.NotImplementedException();
	}
    public void RenvoyerLieu()
    {
         this.getLieu();
    }
	public virtual void supprimerLieu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ajouterAstronautes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void supprimerAstronautes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getListeAstronautes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getLieu()
	{
		throw new System.NotImplementedException();
	}

}

