//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml;

public class Activités
{

    private int idActivité;
    private DateTime heureDebut;
    private string texteDescriptif;
    private string typeActivite;
    private DateTime heureFin;
    private string statutActivite;
	public Activités(string nom, DateTime hDebut, DateTime hFin)
    {
        nbActivité++;
        nomActivité = nom;
        idActivité = nbActivité;
        heureDebut = hDebut;
        heureFin = hFin;
    }

    public Activités()
    {
        nbActivité++;
    }

    private static int nbActivité = 0;
    protected string nomActivité;
    public string GetNomActivité
    {
        get { return nomActivité; }
        set { nomActivité = value; }
    }

    


	public DateTime getHeureDebut
	{
		get { return heureDebut; }
		set { heureDebut = value; }
	}

	public DateTime GetheureFin
	{
		get{return heureFin;}
		set{heureFin=value;}
	}

	public string GettexteDescriptif
	{
		get{return texteDescriptif;}
		set{texteDescriptif=value;}
	}

	public string GettypeActivite
	{
		get{return typeActivite;}
		set{typeActivite=value;}
	}

	public string GetstatutActivite
	{
		get{return statutActivite; }
		set{statutActivite =value;}
	}

	public virtual IEnumerable<Astronautes> listeAstronautes
	{
		get;
		set;
	}

	public virtual void RenvoieActiviteParMotCle()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ajouterLieu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void supprimerLieu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void ajouterAstronautes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void supprimerAstronautes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getListeAstronautes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getLieu()
	{
		throw new System.NotImplementedException();
	}


    /*
public void enregistrerActivites() // Permet d'enregistrer tous les attributs de toutes les classes de tout le projet
{   
     XmlDocument xmlDoc = new XmlDocument ();
	 XmlNode rootNode = xmlDoc.CreateElement("Activités");
	 xmlDoc.AppendChild (rootNode);


	 ////////////Activités//////////// Serialise les attributs de la classe Activités
	 XmlNode Activites=xmlDoc.CreateElement("Activites");
	 rootNode.AppendChild (Activites);

	 XmlNode hDebut= xmlDoc.CreateElement ("heureDebut");
	 hDebut.InnerText = getHeureDebut.ToString();
	 Activites.AppendChild(hDebut);

	 XmlNode hFin = xmlDoc.CreateElement("heureFin"); 
	 hfin.InnerText = GetheureFin.ToString();
	 Activites.AppendChild(GetheureFin);

	 XmlNode txtDescriptif = xmlDoc.CreateElement("texteDescriptif"); 
	 txtDescriptif.InnerText = GettexteDescriptif;
     Activites.AppendChild(txtDescriptif);

	 XmlNode typeActivity = xmlDoc.CreateElement("typeActivite"); 
	 typeActivity.InnerText = GettypeActivite;
	 Activites.AppendChild(typeActivity);

	 XmlNode statutDeActivite = xmlDoc.CreateElement("statutActivite"); 
	 statutDeActivite.InnerText = getstatutActivite;
	 Activites.AppendChild(statutDeActivite);
	 ////////////\Activites////////////
     
    ////////////
 }*/
}

