//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Astronautes
{
	public static int idAstronaute
	{
		get;
		set;
	}

	public virtual string nomAstronaute
	{
		get;
		set;
	}

	public virtual string prenom
	{
		get;
		set;
	}

	public virtual object dateNaissance
	{
		get;
		set;
	}

}

