//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Carte
{
	public virtual IEnumerable<Lieu> listeLieu
	{
		get;
		set;
	}

	public virtual IEnumerable<Exploration> listeExploration
	{
		get;
		set;
	}

	public virtual void getListeLieuExplorer()
	{
		throw new System.NotImplementedException();
	}

}

