//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Exploration : Activités
{

    public Exploration(string tempTypeExploration, string nom, DateTime hDebut, DateTime hFin)
        : base(nom, hDebut, hFin)
    {
        typeExploration = tempTypeExploration;
    }

	public virtual string typeExploration
	{
		get;
		set;
	}

}

