//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Exploration : Activités
{
    private string typeExploration;

    public Exploration(string tempTypeExploration, string nom, DateTime hDebut, DateTime hFin)
        : base(nom, hDebut, hFin)
    {
        typeExploration = tempTypeExploration;
    }

	public string GettypeExploration
	{
        get { return typeExploration; }
        set { typeExploration = value; }
	}

}

