//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Jour
{
    private int idJour;
    private static int nbJour = 0;
    private string etatActivite;
    private Planning PlanningJour;
    private string compteRendu;
    private List<Activités> listeActivite = new List<Activités>(); 

    public string GetetatActivite
    {
        get { return etatActivite; }
        set { etatActivite = value; }
    }
    

    public List<Activités> getlisteActivite
    {
        get{return listeActivite;}
        set{listeActivite=value ;}
    }

	public  Planning GetPlanningJour
	{
        get { return PlanningJour; }
        set { PlanningJour = value; }
	}

	
    public Jour(List<Activités> tempListeActivite) 
    {
        nbJour++;
        listeActivite = tempListeActivite;
        idJour=nbJour;
    }

    public int GetidJour
    {
        get { return idJour; }
        set { idJour = value; }
    }

    public string GetcompteRendu
    {
        get { return compteRendu; }
        set { compteRendu = value; }
    }


	public virtual void ajouterActivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifierActivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void supprimerActivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void modifierCompteRendu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void clearActivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void getListeActivite()
	{
		throw new System.NotImplementedException();
	}

	public virtual void motCleContenuDansCR()
	{
		throw new System.NotImplementedException();
	}

	public virtual void motCleContenuDansTDActivite()
	{
		throw new System.NotImplementedException();
	}

}

