//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Lieu
{
    private string nomLieu;
    private double[] tabCoordonnees = new double[2];
    private int idLieu;
    private static int nbLieu;
    private List<Activités> listeActivites = new List<Activités>();
    //Constructeur par défaut
    public Lieu()
    {
        nbLieu++;
        idLieu = nbLieu;
    }
	public string GetnomLieu
	{
        get { return nomLieu; }
        set { nomLieu = value; }
	}
    public int GetidLieu
    {
        get { return idLieu; }
        set { idLieu = value; }
    }
    public double GettabCoordonnees
	{
        get{return tabCoordonnees[];}
        set
        {
            for(int j=0;j<2;j++)
            {
                tabCoordonnees[j] = value;
            }
        }
		
	}

	public List<Activités> GetlisteActivites
	{
        get { return listeActivites; }
        set { listeActivites = value; }
	}

}

