//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Lieu
{
    //Constructeur par défaut
    public Lieu()
    {

    }
	public virtual string nomLieu
	{
		get;
		set;
	}

	public virtual object coordonnées
	{
		get;
		set;
	}

	public static int idLieu
	{
		get;
		set;
	}

	public virtual IEnumerable<Activités> listeActivite
	{
		get;
		set;
	}

}

